name: Code Review AI

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main # target branch of the PR.

jobs:
  run-code-review:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Debug FASTAPI_URL
        run: echo "FastAPI URL is ${{ secrets.REVIEW_API_URL }}"

      - name: Call FastAPI Review Agent
        env:
          FASTAPI_URL: ${{ secrets.REVIEW_API_URL }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Triggering code review for PR #${{ github.event.pull_request.number }}..."
          echo "FastAPI URL: $FASTAPI_URL/review/"

          curl -v -X POST "$FASTAPI_URL/review/" \
            -H "Content-Type: application/json" \
            -d "{\"repo_url\": \"https://github.com/${{ github.repository }}\", \"pr_number\": ${{ github.event.pull_request.number }}, \"branch\": \"${{ github.head_ref }}\", \"changed_files\": []}"